import React from 'react'
import Head from 'next/head'
import type { NextPage } from 'next'
import Navbar from '@components/Navbar'
import { Box, Text, Image, Tag } from '@chakra-ui/react'
import Loading from '@components/Loading'
import animationData from '../../public/assets/shape-geometrics.json'
import animationFlow from '../../public/assets/75794-diferencia-legal.json'
import 'react-multi-carousel/lib/styles.css'
import Footer from '@components/Footer'
import Hero from '@components/Hero'
import Introduction from '@components/modules/displays/Introduction'
import FocusedText from '@components/modules/displays/FocusedText'
import ProjectShowcase from '@components/modules/displays/ProjectShowCase'
import Blogs from '@components/modules/displays/Blog/Blogs'
import GetInTouch from '@components/modules/displays/GetInTouch'

const Home: NextPage = () => {
  const [loading, setLoading] = React.useState<boolean>(true)

  React.useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false)
    }, 1)
    return () => clearTimeout(timer)
  }, [])

  if (loading) {
    return <Loading />
  }

  return (
    <>
      <Head>
        <title>Albarms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="shortcut icon" href="/static/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Introduction />
      <FocusedText />
      <ProjectShowcase />
      <Blogs />
      <GetInTouch />
      <Footer />
    </>
  )
}

export default Home
