import React from 'react'
import Head from 'next/head'
import type { NextPage } from 'next'
import Navbar from '@components/Navbar'
import {
  Box,
  Container,
  Flex,
  Text,
  Image,
  Center,
  HStack,
  Tag,
  IconButton,
} from '@chakra-ui/react'
import Loading from '@components/Loading'
import Lottie from 'react-lottie'
import animationData from '../../public/assets/shape-geometrics.json'
import animationFlow from '../../public/assets/75794-diferencia-legal.json'
import Carousel from 'react-multi-carousel'
import 'react-multi-carousel/lib/styles.css'
import { BsDiscord, BsInstagram, BsGithub, BsLinkedin } from 'react-icons/bs'
import Footer from '@components/Footer'
import Hero from '@components/Hero'
import Introduction from '@components/modules/displays/Introduction'
import FocusedText from '@components/modules/displays/FocusedText'
import ProjectShowcase from '@components/modules/displays/ProjectShowCase'
import Blogs from '@components/modules/displays/Blog/Blogs'
import GetInTouch from '@components/modules/GetInTouch'

const defaultOptions = {
  loop: true,
  autoplay: true,
  animationData: animationData,
  rendererSettings: {
    preserveAspectRatio: 'xMidYMid slice',
  },
}
const flowAnimationSetting = {
  loop: true,
  autoplay: true,
  animationData: animationFlow,
  rendererSettings: {
    preserveAspectRatio: 'xMidYMid slice',
  },
}

const Home: NextPage = () => {
  const [loading, setLoading] = React.useState<boolean>(false)

  if (loading) {
    return <Loading />
  }

  const responsive = {
    superLargeDesktop: {
      breakpoint: { max: 4000, min: 3000 },
      items: 8.5,
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 6.3,
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 4,
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 3,
    },
  }

  const responsiveProject = {
    superLargeDesktop: {
      breakpoint: { max: 4000, min: 3000 },
      items: 3,
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 2.6,
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1.2,
    },
  }

  const responsiveBlogs = {
    superLargeDesktop: {
      breakpoint: { max: 4000, min: 3000 },
      items: 5,
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 4.5,
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1.2,
    },
  }

  const SquareCard: React.FC<{ item: any }> = ({ item }) => {
    return (
      <Box>
        <Image
          boxSize="80px"
          objectFit="cover"
          src="https://miro.medium.com/max/816/1*mn6bOs7s6Qbao15PMNRyOA.png"
          alt={item}
        />
      </Box>
    )
  }

  const ProjectCard: React.FC<{ item: any }> = ({ item }) => {
    return (
      <Box>
        <Image
          w="420px"
          h="280px"
          objectFit="contain"
          src="../assets/project-1.jpg"
          alt={item}
        />
      </Box>
    )
  }

  const BlogCard: React.FC<{ item: any }> = ({ item }) => {
    return (
      <Box w="220px">
        <Tag variant="solid" colorScheme="teal" size="sm" mb="4">
          Teal
        </Tag>
        <Text className="text-md font-semibold text-justify">
          Five Ways Tech Startups Are Different from Other Small and
          Medium-Sized Enterprises
        </Text>{' '}
      </Box>
    )
  }

  return (
    <>
      <Head>
        <title>Albarms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Introduction />
      <FocusedText />
      <ProjectShowcase />
      <Blogs />
      <GetInTouch />
      <Footer />
    </>
  )
}

export default Home
